# Generated by Django 4.0.3 on 2022-05-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_product_delete_monitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['firm', 'name'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
    ]
