# Generated by Django 4.0.3 on 2022-06-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0006_alter_product_available_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
